name: GitHub Security Alerts for Jira

on: 
 workflow_dispatch

jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
     - name: "test"
       env:
          GH_SECURITY_TOKEN: ${{ secrets.GITHUBPT }}
          JIRA_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT: PGS
          JIRA_ISSUE_TYPE: Incident
          JIRA_ISSUE_LABELS: Dependabot
       run: |
        jira_ticket() {
        cat <<- EOF
            {
         "fields":{
         "project":{
         "key":"PGS"
         },
        "summary":"Dependabot-summary-test",
        "description":"Dependabot description",
        "issuetype":{
         "name":"Incident"
        },
        "priority":{
         "name":"Low"
        },
        "customfield_10025":{
          "value":"No"
        },
        "labels":[
         "Dependabot"
         ]
        }
        }
        EOF
        }
          curl -sH "Authorization: Bearer ${JIRA_TOKEN}" -X POST --data "$(jira_ticket)" \
                             -H "Content-Type: application/json" https://jira.sixt.com/rest/api/2/issue/
          
       shell: bash
