name: Dependabot fetch metadata
on: pull_request

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.actor == 'keerthana2022' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          alert-lookup: true
          compat-lookup: true
          github-token: "${{ secrets.PAT_TOKEN }}"
        env:
         Ghsa-id: ${{ steps.dependabot-metadata.outputs.ghsa-id }}
      - name: test
        run: |
          echo $Ghsa-id
        shell: bash
