name: GitHub Security Alerts for Jira

on: 
 workflow_dispatch

jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
     - name: "test"
       env:
          GH_SECURITY_TOKEN: ${{ secrets.GITHUBPT }}
          JIRA_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT: PGS
          JIRA_ISSUE_TYPE: Incident
          JIRA_ISSUE_LABELS: Dependabot
       run: |
          curl -H "Authorization: Bearer $JIRA_TOKEN" -X GET -H "Content-Type: application/json" https://jira.sixt.com/rest/api/2/search 
       shell: bash
